use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "PASTE_YOUR_RANDOM_KEY_HERE"
  limiter: false
  public_instance: false

search:
  formats:
    - html
    - json
